const respMsg = {
    isAlreadyExist: "is already exist",
    doesNotExist: "does not exist",
    invalidCredential: "Invalid credential",
    noToken: "No Bearer token provided.",
    invExpToken: "Invalid or Expired token",
    loggedInSuccess: "Logged in successfully",
    registeredSuccess: "Registered successfully",
    updatedSuccess: "updated successfully",
    addedSuccess: "added successfully",
    deletedSuccess: "deleted successfully",
    noDataFound: "No data found",
    nameReq: "Name is required.",
    nameValMsg: "Name can only contain alphabets, numaric and spaces.",
    pondValMsg: "Pond can only contain alphabets and spaces.",
    districtReq: "District is required.",
    districtValMsg: "District can only contain alphabets and spaces.",
    pondReq: "Pond is required.",
    latitudeReq: "Latitude is required.",
    latitudeValMsg: "Latutude can only contain numaric and .",
    longitudeReq: "Longitude is required.",
    longitudeValMsg: "Longitude can only contain numaric and .",
    talukReq: "Taluk is required.",
    talukValMsg: "Taluk can only contain alphabets and spaces.",
    villageReq: "Village is required.",
    villageValMsg: "Village can only contain alphabets and spaces.",
    fileReq: "File is required.",
    uniqueIdReq: "Unique Id is required.",
    uniqueIdValMsg: "Unique Id can only contain alphabets, numaric and spaces.",
    defaultReq: "is required.",
    defaultNameValMsg: "can only contain alphabets and spaces.",
    defaultNamewithCommaValMsg: "can only contain alphabets comma and spaces.",
    defaultNameWithNumaricValMsg: "can only contain alphabets, numaric and spaces.",
    defaultNumberValMsg: "can only contain numaric values.",
    defaultBooleanValMsg: " accept True of false only",
    reviewApproved: "Review Approved successfully",
    mobReq: "Mobile Number is required",
    mobileValMsg: 'Mobile number cannot consist solely of zeros or start with zero and must be 10 digit',
    emailValMsg: 'Invalid email address',
    emailReq: 'Email is required',
}

module.exports = respMsg;